### ISSUE TITLE
"go searchmoves" doesnt work

### ISSUE THREAD

**Issue by LocutusOfPenguin** [DanielWhite94/robocide#1]
tried several ways, but i always get "e4"

./robocide 
go movetime 10 searchmoves c2c3 g2g4
info depth 1
info nodes 2 time 0 hashfull 0
info depth 1 score cp 20 nodes 22 time 0 pv e2e4
info depth 2
info depth 2 score cp 2 nodes 103 time 0 pv e2e4 e7e5
info depth 3
info depth 3 score cp 17 nodes 844 time 0 pv d2d4 d7d5 c1f4
info depth 4
info depth 4 score cp 2 nodes 2634 time 2 nps 1317000 pv d2d4 d7d5 c1f4 c8f5
info depth 5
info depth 5 score cp 9 nodes 10110 time 6 nps 1685000 pv e2e4 d7d5 e4d5 d8d5 d2d4
info depth 6
bestmove e2e4 ponder d7d5
quit

**Comment by DanielWhite94** [comment]
'searchmoves' isn't yet implemented I'm afraid but perhaps if I get time in the next few weeks I'll have a look at adding it.

**Comment by LocutusOfPenguin** [comment]
In meantime i tried to fix it myself (not too successful - problems with mate). see here:
https://github.com/LocutusOfPenguin/robocide

but mk-chan (i asked him to help me) have a working version now see here:
https://github.com/Mk-Chan/robocide
He also changed your code on other places (search).

the mk-chan version i'm using for our project picochess right now.

**Comment by DanielWhite94** [comment]
This feature has now been implemented on the Development branch and will be included in the next release.
