### ISSUE TITLE
Robocide for android

### ISSUE THREAD

**Issue by khuttur** [DanielWhite94/robocide#2]
Hello Daniel,

Can you make it for android?
Or what is its elo rating?

**Comment by DanielWhite94** [comment]
Unfortunately, I'll be honest I have no idea what it would take to get it working on Android and it is not something I plan to do.

As for rating, on [CCRL 40/4](http://www.computerchess.org.uk/ccrl/404/cgi/engine_details.cgi?print=Details&each_game=1&eng=Robocide%2020170718%2064-bit#Robocide_20170718_64-bit) it scores 2242 - although I must admit I am not sure exactly which version was tested.
